/*
Nextlinux Engine API Server

This is the Nextlinux Engine API. Provides the primary external API for users of the service.

API version: 0.6.0
Contact: nurmi@nextlinux.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package engine

import (
	"encoding/json"
)

// NextlinuxImageTagSummary A unique image in the engine.
type NextlinuxImageTagSummary struct {
	ImageDigest *string `json:"imageDigest,omitempty"`
	ParentDigest *string `json:"parentDigest,omitempty"`
	ImageId *string `json:"imageId,omitempty"`
	AnalysisStatus *string `json:"analysis_status,omitempty"`
	Fulltag *string `json:"fulltag,omitempty"`
	CreatedAt *int32 `json:"created_at,omitempty"`
	AnalyzedAt *int32 `json:"analyzed_at,omitempty"`
	TagDetectedAt *int32 `json:"tag_detected_at,omitempty"`
	ImageStatus *string `json:"image_status,omitempty"`
}

// NewNextlinuxImageTagSummary instantiates a new NextlinuxImageTagSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNextlinuxImageTagSummary() *NextlinuxImageTagSummary {
	this := NextlinuxImageTagSummary{}
	return &this
}

// NewNextlinuxImageTagSummaryWithDefaults instantiates a new NextlinuxImageTagSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNextlinuxImageTagSummaryWithDefaults() *NextlinuxImageTagSummary {
	this := NextlinuxImageTagSummary{}
	return &this
}

// GetImageDigest returns the ImageDigest field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetImageDigest() string {
	if o == nil || o.ImageDigest == nil {
		var ret string
		return ret
	}
	return *o.ImageDigest
}

// GetImageDigestOk returns a tuple with the ImageDigest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetImageDigestOk() (*string, bool) {
	if o == nil || o.ImageDigest == nil {
		return nil, false
	}
	return o.ImageDigest, true
}

// HasImageDigest returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasImageDigest() bool {
	if o != nil && o.ImageDigest != nil {
		return true
	}

	return false
}

// SetImageDigest gets a reference to the given string and assigns it to the ImageDigest field.
func (o *NextlinuxImageTagSummary) SetImageDigest(v string) {
	o.ImageDigest = &v
}

// GetParentDigest returns the ParentDigest field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetParentDigest() string {
	if o == nil || o.ParentDigest == nil {
		var ret string
		return ret
	}
	return *o.ParentDigest
}

// GetParentDigestOk returns a tuple with the ParentDigest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetParentDigestOk() (*string, bool) {
	if o == nil || o.ParentDigest == nil {
		return nil, false
	}
	return o.ParentDigest, true
}

// HasParentDigest returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasParentDigest() bool {
	if o != nil && o.ParentDigest != nil {
		return true
	}

	return false
}

// SetParentDigest gets a reference to the given string and assigns it to the ParentDigest field.
func (o *NextlinuxImageTagSummary) SetParentDigest(v string) {
	o.ParentDigest = &v
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetImageId() string {
	if o == nil || o.ImageId == nil {
		var ret string
		return ret
	}
	return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetImageIdOk() (*string, bool) {
	if o == nil || o.ImageId == nil {
		return nil, false
	}
	return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasImageId() bool {
	if o != nil && o.ImageId != nil {
		return true
	}

	return false
}

// SetImageId gets a reference to the given string and assigns it to the ImageId field.
func (o *NextlinuxImageTagSummary) SetImageId(v string) {
	o.ImageId = &v
}

// GetAnalysisStatus returns the AnalysisStatus field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetAnalysisStatus() string {
	if o == nil || o.AnalysisStatus == nil {
		var ret string
		return ret
	}
	return *o.AnalysisStatus
}

// GetAnalysisStatusOk returns a tuple with the AnalysisStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetAnalysisStatusOk() (*string, bool) {
	if o == nil || o.AnalysisStatus == nil {
		return nil, false
	}
	return o.AnalysisStatus, true
}

// HasAnalysisStatus returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasAnalysisStatus() bool {
	if o != nil && o.AnalysisStatus != nil {
		return true
	}

	return false
}

// SetAnalysisStatus gets a reference to the given string and assigns it to the AnalysisStatus field.
func (o *NextlinuxImageTagSummary) SetAnalysisStatus(v string) {
	o.AnalysisStatus = &v
}

// GetFulltag returns the Fulltag field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetFulltag() string {
	if o == nil || o.Fulltag == nil {
		var ret string
		return ret
	}
	return *o.Fulltag
}

// GetFulltagOk returns a tuple with the Fulltag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetFulltagOk() (*string, bool) {
	if o == nil || o.Fulltag == nil {
		return nil, false
	}
	return o.Fulltag, true
}

// HasFulltag returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasFulltag() bool {
	if o != nil && o.Fulltag != nil {
		return true
	}

	return false
}

// SetFulltag gets a reference to the given string and assigns it to the Fulltag field.
func (o *NextlinuxImageTagSummary) SetFulltag(v string) {
	o.Fulltag = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetCreatedAt() int32 {
	if o == nil || o.CreatedAt == nil {
		var ret int32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetCreatedAtOk() (*int32, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int32 and assigns it to the CreatedAt field.
func (o *NextlinuxImageTagSummary) SetCreatedAt(v int32) {
	o.CreatedAt = &v
}

// GetAnalyzedAt returns the AnalyzedAt field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetAnalyzedAt() int32 {
	if o == nil || o.AnalyzedAt == nil {
		var ret int32
		return ret
	}
	return *o.AnalyzedAt
}

// GetAnalyzedAtOk returns a tuple with the AnalyzedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetAnalyzedAtOk() (*int32, bool) {
	if o == nil || o.AnalyzedAt == nil {
		return nil, false
	}
	return o.AnalyzedAt, true
}

// HasAnalyzedAt returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasAnalyzedAt() bool {
	if o != nil && o.AnalyzedAt != nil {
		return true
	}

	return false
}

// SetAnalyzedAt gets a reference to the given int32 and assigns it to the AnalyzedAt field.
func (o *NextlinuxImageTagSummary) SetAnalyzedAt(v int32) {
	o.AnalyzedAt = &v
}

// GetTagDetectedAt returns the TagDetectedAt field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetTagDetectedAt() int32 {
	if o == nil || o.TagDetectedAt == nil {
		var ret int32
		return ret
	}
	return *o.TagDetectedAt
}

// GetTagDetectedAtOk returns a tuple with the TagDetectedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetTagDetectedAtOk() (*int32, bool) {
	if o == nil || o.TagDetectedAt == nil {
		return nil, false
	}
	return o.TagDetectedAt, true
}

// HasTagDetectedAt returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasTagDetectedAt() bool {
	if o != nil && o.TagDetectedAt != nil {
		return true
	}

	return false
}

// SetTagDetectedAt gets a reference to the given int32 and assigns it to the TagDetectedAt field.
func (o *NextlinuxImageTagSummary) SetTagDetectedAt(v int32) {
	o.TagDetectedAt = &v
}

// GetImageStatus returns the ImageStatus field value if set, zero value otherwise.
func (o *NextlinuxImageTagSummary) GetImageStatus() string {
	if o == nil || o.ImageStatus == nil {
		var ret string
		return ret
	}
	return *o.ImageStatus
}

// GetImageStatusOk returns a tuple with the ImageStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NextlinuxImageTagSummary) GetImageStatusOk() (*string, bool) {
	if o == nil || o.ImageStatus == nil {
		return nil, false
	}
	return o.ImageStatus, true
}

// HasImageStatus returns a boolean if a field has been set.
func (o *NextlinuxImageTagSummary) HasImageStatus() bool {
	if o != nil && o.ImageStatus != nil {
		return true
	}

	return false
}

// SetImageStatus gets a reference to the given string and assigns it to the ImageStatus field.
func (o *NextlinuxImageTagSummary) SetImageStatus(v string) {
	o.ImageStatus = &v
}

func (o NextlinuxImageTagSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ImageDigest != nil {
		toSerialize["imageDigest"] = o.ImageDigest
	}
	if o.ParentDigest != nil {
		toSerialize["parentDigest"] = o.ParentDigest
	}
	if o.ImageId != nil {
		toSerialize["imageId"] = o.ImageId
	}
	if o.AnalysisStatus != nil {
		toSerialize["analysis_status"] = o.AnalysisStatus
	}
	if o.Fulltag != nil {
		toSerialize["fulltag"] = o.Fulltag
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.AnalyzedAt != nil {
		toSerialize["analyzed_at"] = o.AnalyzedAt
	}
	if o.TagDetectedAt != nil {
		toSerialize["tag_detected_at"] = o.TagDetectedAt
	}
	if o.ImageStatus != nil {
		toSerialize["image_status"] = o.ImageStatus
	}
	return json.Marshal(toSerialize)
}

type NullableNextlinuxImageTagSummary struct {
	value *NextlinuxImageTagSummary
	isSet bool
}

func (v NullableNextlinuxImageTagSummary) Get() *NextlinuxImageTagSummary {
	return v.value
}

func (v *NullableNextlinuxImageTagSummary) Set(val *NextlinuxImageTagSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableNextlinuxImageTagSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableNextlinuxImageTagSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNextlinuxImageTagSummary(val *NextlinuxImageTagSummary) *NullableNextlinuxImageTagSummary {
	return &NullableNextlinuxImageTagSummary{value: val, isSet: true}
}

func (v NullableNextlinuxImageTagSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNextlinuxImageTagSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


